-- Create a stage, copy a file from a Git repository, and load it into a table
-- Co-authored with CoCo
SHOW GIT REPOSITORIES;

LS @TASTY_BYTES_DBT_DB.PUBLIC.MY_SNOWFLAKE_REPO/branches/main/;

CREATE OR REPLACE STAGE TASTY_BYTES_DBT_DB.PUBLIC.DATA_STAGE;

COPY FILES INTO @TASTY_BYTES_DBT_DB.PUBLIC.DATA_STAGE FROM @TASTY_BYTES_DBT_DB.PUBLIC.MY_SNOWFLAKE_REPO/branches/main/files/annual-enterprise-survey-2025-financial-year-provisional.csv;


LS @TASTY_BYTES_DBT_DB.PUBLIC.DATA_STAGE;

CREATE OR REPLACE FILE FORMAT TASTY_BYTES_DBT_DB.PUBLIC.CSV_FF TYPE = 'CSV' SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE TABLE TASTY_BYTES_DBT_DB.PUBLIC.ANNUAL_ENTERPRISE_SURVEY (
    YEAR INT,
    INDUSTRY_AGGREGATION_NZSIOC VARCHAR,
    INDUSTRY_CODE_NZSIOC VARCHAR,
    INDUSTRY_NAME_NZSIOC VARCHAR,
    UNITS VARCHAR,
    VARIABLE_CODE VARCHAR,
    VARIABLE_NAME VARCHAR,
    VARIABLE_CATEGORY VARCHAR,
    VALUE VARCHAR,
    INDUSTRY_CODE_ANZSIC06 VARCHAR
);

COPY INTO TASTY_BYTES_DBT_DB.PUBLIC.ANNUAL_ENTERPRISE_SURVEY
FROM @TASTY_BYTES_DBT_DB.PUBLIC.DATA_STAGE/annual-enterprise-survey-2025-financial-year-provisional.csv
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
